### ISSUE TITLE
Пропадает точка при скролле

### ISSUE THREAD

**Issue by LeoDubinin** [Chamber6821/berega-map#3]
https://drive.google.com/file/d/1EpXjmib9Q8_ElogYhY3LkM7b5nidTv8b/view?usp=sharing

**Comment by Chamber6821** [comment]
Она пропадает, потому что не попадает ни в какое здание. При зуме маркеры скрываются и появляются здания

**Comment by LeoDubinin** [comment]
Она не должна пропадать, должна просто отображаться также точкой если нет дома

**Comment by Chamber6821** [comment]
Исправлено в #30
