### ISSUE TITLE
При выборе новостроек также отображаются и дома

### ISSUE THREAD

**Issue by LeoDubinin** [Chamber6821/berega-map#5]
![photo_2024-08-12_12-50-21](https://github.com/user-attachments/assets/d518e9eb-68e7-4517-bc35-2446044abfcb)

**Comment by Chamber6821** [comment]
Этот [PR](https://github.com/Chamber6821/berega-map/issues/7#8) должен был исправить эту ошибку. Теперь маркера отображаются корректно? (там есть ссылка на превью)

**Comment by Chamber6821** [comment]
Дублирует #7. Обсуждение продолжиться там
