### ISSUE TITLE
Некоторые точки отображаются в море

### ISSUE THREAD

**Issue by LeoDubinin** [Chamber6821/berega-map#6]
![photo_2024-08-12_12-50-54](https://github.com/user-attachments/assets/64e0687a-73f7-496a-affa-7729174f3871)

**Comment by LeoDubinin** [comment]
https://drive.google.com/file/d/1TYahmMiS5fxwyF28omle9VU3dBGYYge6/view?usp=sharing

**Comment by Chamber6821** [comment]
Это проблема с данными в БД берегов
