### ISSUE TITLE
Selecting one filter by room

### ISSUE THREAD

**Issue by vladvg8** [Chamber6821/berega-map#65]
При переключении API на `Внешнее` выбор фильтра по кол-ву комнат должен производится лишь по одному параметру. При нажатии на уже выбранный элемент, фильтрация по комната сбрасывается.
Решение должно быть как в FiltersHeader, так и в FiltersPopup

**Comment by Chamber6821** [comment]
При нажатии на уже выбранный пункт должно полностью сбрасываться? Например если были выбраны комнаты `1` `2` `4` мы нажимаем на `4` и у нас снимается выделение со всех вариантов?

**Comment by vladvg8** [comment]
Данная реализация только для внешнего api

**Comment by Chamber6821** [comment]
Зачем?

**Comment by Chamber6821** [comment]
Чем не угодила дефолтная реализация?

**Comment by vladvg8** [comment]
Api не поддерживает такую реализацию, а делать много запросов, которые отличаются выбраными элементами смысла нет. Представь, что у тебя выбраны все варианты фильтров по комнатам, так же несколько типов недвижимости, и мы получаем много запросов, которые будут грузится вечность и будут нагружать клиента

**Comment by vladvg8** [comment]
Как минимум так решила Ваутика сделать. Если у тебя есть решение получше, то можно вернуть старую реализацию

**Comment by Chamber6821** [comment]
Окей, тогда сделай так же, как сделано для `FilterGroup`, он сделан на базе `useVariantInput`, но поведение такое же какое тебе нужно

**Comment by vladvg8** [comment]
Так проблема в том, что для Встроенного API требуется стандартная реализация, а для Внешнего другая уже, как для FilterGroup. Я не могу динамически менять компоненты для выбора, выдает ошибку
