### ISSUE TITLE
При выборе вторички также отображаются и земельные участки

### ISSUE THREAD

**Issue by LeoDubinin** [Chamber6821/berega-map#7]
![photo_2024-08-12_13-40-32](https://github.com/user-attachments/assets/7819d967-20fd-4b7d-9e64-dd3c8c712b81)

**Comment by Chamber6821** [comment]
Этот [PR](#8) должен был исправить эту ошибку. Теперь маркера отображаются корректно? (там есть ссылка на превью)

**Comment by Chamber6821** [comment]
Тупанул, вот сразу ссылка на [превью](https://vercel.live/open-feedback/berega-map-git-feat-upgrade-filters-ivan-osinins-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)

**Comment by Chamber6821** [comment]
Исправлено в #8
